### ISSUE TITLE
Publish `ruby-lsp` to Open VSX

### ISSUE THREAD

**Issue by moritonal** [Shopify/vscode-ruby-lsp#401]
Dear extension author,
Please publish this extension to the Open VSX marketplace. Developers are increasingly using tools like GitPod to democratise access to development environments, and cannot currently use their Web versions due our projects dependency on `ruby-lsp` which can only be accessed via Microsoft's extension marketplace currently.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by moritonal** [comment]
Ah, thanks for moving it. 

Could you clarify slightly? You closed my request because you haven't had any requests for it, or because you haven't had enough requests? I'll be attending a Gitlab meet soon and try drum up support. 

No problem either way, I'll fork and be owner for it on their side. Message me if you want to takeover in the future.

Tom

**Comment by andyw8** [comment]
After some further discussion with the team, we will look into publishing on Open VSX sometime soon, so please hold off on submitting a fork.

**Comment by yuri-becker** [comment]
Add me to the list

**Comment by andyw8** [comment]
Our legal department is reviewing the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php). Once that that is done, we hope to publish the extension on Open VSX.

**Comment by jay7x** [comment]
Any chance to get it published soon? Just found that rebornix plugin doesn't work for me anymore..

**Comment by trinitronx** [comment]
+1 to this request.

As seen above, there are others who would love to use this extension but currently can't find it due to the split between OpenVSX / VisualStudio Marketplace repos for OSS builds of VSCode.

Currently the older `vscode-ruby` extension is available on OpenVSX, but [has been deprecated][2].  This currently leaves the [Ruby Solargraph][3] extension as the only viable alternative for VSCode OSS & Linux users.

In the past few years, many OSS Linux packagers of VSCode, VSCodium, (a.k.a. Code OSS) have moved to using [OpenVSX extension Registry][openvsx] and had to [disable Microsoft's Extensions Marketplace by default][1] due to Microsoft's licensing restrictions (whether they be perceived or actual :shrug:).

So, in order for most Linux developers using stock OSS-packaged versions of VSCode to find extensions such as this one, it's important to also publish to OpenVSX.

It's pretty simple to implement dual publishing via a [GitHub Actions workflow described here][doc]. It probably wouldn't take long to accomplish and would allow for easy deployment through GitHub Actions CI/CD.

[1]: https://www.reddit.com/r/vscode/comments/kb0eb5/extensions_missing/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1
[openvsx]: https://open-vsx.org/
[doc]: https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md
[2]: https://github.com/rubyide/vscode-ruby
[3]: https://marketplace.visualstudio.com/items?itemName=castwide.solargraph&ssr=false#review-details

**Comment by backpackerhh** [comment]
Another one interested right here :point_up:

**Comment by andyw8** [comment]
We've published on OpenVSX, please try it and let us know if it works for you:

https://open-vsx.org/extension/Shopify/ruby-lsp

**Comment by jirutka** [comment]
Do you understand that this is not a one-shot action – every new release should be published to OpenVSX, i.e. it should be done automatically via CI, the same as for the Microsoft marketplace? The latest version on OpenVSX is 0.4.13, but I see 0.4.20 in this repository.

**Comment by andyw8** [comment]
Future releases should be automatically published to OpenVSX.
