### ISSUE TITLE
Ruby Version Manager: frum

### ISSUE THREAD

**Issue by naxels** [Shopify/vscode-ruby-lsp#514]
Hi team,

Just switched to using Ruby LSP / Ruby extension in VSCode and noticed that
my Version Manager, frum is not supported.

https://github.com/TaKO8Ki/frum

Could support be added, now the extensions fails as it's trying to work with macOS Ruby.

Thank you and keep up the good work!

**Comment by vinistock** [comment]
Hey! Thank you so much for the kind words and the contribution.

I think instead of adding more and more version managers to that list, we should provide a more customizable way for people using less common options. This should also help folks who aren't using a version manager such as in #517.

We'll think about how to support this more widely to allow you to use frum.
