### ISSUE TITLE
Using a custom path while using system gems is unsupported

### ISSUE THREAD

**Issue by SanterreJo** [Shopify/vscode-ruby-lsp#536]
The extension fails during initialization with the following output:

```
>> Running `bundle install`...
ERROR> Using a custom path while using system gems is unsupported.
ERROR> 
ERROR> path:
ERROR> Set via BUNDLE_PATH: "/bundle/vendor"
ERROR> 
ERROR> path.system:
ERROR> Set via BUNDLE_PATH__SYSTEM: true
ERROR> 
ERROR> disable_shared_gems:
ERROR> You have not configured a value for `disable_shared_gems`
>> `bundle install` exited with code 15
```

Environment:
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [aarch64-linux]
vscode: 1.77.0
vscode-ruby-lsp: 0.2.3
bundler: 2.4.10

The environment runs inside a docker container using the environment variable `BUNDLE_PATH=/bundle/vendor`.
I use this environment variable to persist gems inside the vscode devcontainer.

Looking at the code, I can see that the BUNDLE_PATH__SYSTEM is always set to true. 
https://github.com/Shopify/vscode-ruby-lsp/blob/09691bd596be17574512adf5d1aebae79e6fe74f/src/ruby.ts#L210-L212

Am I missing something in the configuration? Does vscode-ruby-lsp support a custom BUNDLE_PATH in any way?

**Comment by ryansch** [comment]
This issue also affects [devenv.sh](https://devenv.sh/) users.

**Comment by xeron** [comment]
Similar issue. My whole project bundle in being installed into global gems by the extension while I'm trying to keep everything local:

```
$ cat .bundle/config
---
BUNDLE_PATH: "bundle"
BUNDLE_DISABLE_SHARED_GEMS: "true"
```

**Comment by jirutka** [comment]
I’m experiencing the same problem when running VS Code in Flatpak. Please don’t hard-code `BUNDLE_PATH__SYSTEM`!

**Comment by ThomasOwens** [comment]
I'm also getting this error while using VS Code and Devcontainers.

I wonder if it's related to https://github.com/devcontainers/templates/issues/188. I had to manually and explicitly set values for `BUNDLE_APP_CONFIG` and `BUNDLE_PATH` in my `devcontainer.json` file because there were `Bundler::PermissionError`s. It seems like a container image uses RVM (not sure why you'd need RVM inside a container for a specific application - this seems like each application would have its own Ruby version and use the appropriate container) and Bundler doesn't have permission to write there. However, since I had to do this to get my app developing going, I don't know if this is a cause or not.
