### ISSUE TITLE
Unable to disable semantic highlighting

### ISSUE THREAD

**Issue by ryanb** [Shopify/vscode-ruby-lsp#537]
I have `semanticHighlighting` config set to `false` yet it's still overriding the default syntax highlighting grammars. I believe this is due to the grammar file built into the extension from #187.

Is there a way to disable this?

**Comment by vinistock** [comment]
The problem is that Ruby's syntax is ambiguous and we can never correctly highlight it without the server. For example, if you have a line that just has `foo` in it, it's impossible to tell if it's a local variable or method invocation with a regex (which is what grammars use).

That's where semantic highlighting comes in, it parses the Ruby file and determines what exactly that piece of code is supposed to be. Is there any reason why you can't use semantic highlighting?

In my experience, most themes don't do a great job at highlighting Ruby. If I may recommend a different one, our [extension pack](https://github.com/Shopify/vscode-shopify-ruby#themes) bundles a theme that uses all of the Ruby LSP semantic highlighting information.

**Comment by ryanb** [comment]
@vinistock

> That's where semantic highlighting comes in, it parses the Ruby file and determines what exactly that piece of code is supposed to be. Is there any reason why you can't use semantic highlighting?

I plan to. I just need to configure my theme to support it. I'll check out the extension pack, thanks for the link!

As for this issue, it looks like the [motivation for adding a grammar file](https://github.com/Shopify/vscode-ruby-lsp/issues/139) is to provide a fallback for when the LSP isn't available. Can this be done with a separate extension? This way one can opt-in to it or use an alternative extension for grammars if they prefer.

If that isn't an option, are you open to improvements to the grammar file?
