### ISSUE TITLE
PATH is ignored

### ISSUE THREAD

**Issue by jonjonw** [Shopify/vscode-ruby-lsp#542]
The plugin doesn't seem to use $PATH to locate the bundle command. It appears to be using the system-wide ruby instead of the one in my $PATH. I have Version Manager set to 'None'.

```
$ which ruby
/Users/jon/.rubies/ruby-3.2.2/bin/ruby
$ which bundle
/Users/jon/Projects/ledger/ruby/bin/bundle
$ ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin20]
$ bundle --version
Bundler version 2.4.10
```

The error in the output tab in vscode:
```
[Error - 7:29:24 PM] Starting client failed
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.4.10) required by your /Users/jon/Projects/ledger/ruby/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.4.10`
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/bin/bundle:23:in `<main>'
```

**Comment by jonjonw** [comment]
I should also mention that I did check:

```
$ grep ruby-lsp /Users/jon/Projects/ledger/ruby/Gemfile
$ grep ruby-lsp /Users/jon/Projects/ledger/ruby/Gemfile.lock
```

```BUNDLE_GEMFILE=/path/to/your/project/.ruby-lsp/Gemfile bundle install```
ran without any errors

and ran `Developer: Reload window` but I still have the same issue.

**Comment by andyw8** [comment]
@jonjonw I assume you're appending `/Users/jon/.rubies/ruby-3.2.2/bin/` to the `PATH`? Where is that being done, e.g. inside `.zshrc`?

**Comment by jonjonw** [comment]
> In case you're not using a version manager and are just putting the Ruby path manually yourself, #507 will fix this.

Thanks! Just updated and it's working great now!

**Comment by jonjonw** [comment]
Ok - I see the problem.

I'm using a [direnv extension](https://github.com/direnv/direnv-vscode) to set the PATH from .envrc. It seems that ruby-lsp is reading the PATH before the other extension updates it and continues to use the old PATH when restarted.

So it works fine when I load vscode from the project directory ie `cd Projects/ledger && vscode .` but if I load vscode from the GUI or another directory, it depends on the vscode-direnv extension to set the PATH - which it does but seemingly after the ruby-lsp extension reads/saves the PATH.

I wonder if if any of the following work-arounds might be easy to implement:

- Have an option to have ruby-lsp load later (after other extensions
- Add a version manager setting for direnv and run something like `direnv exec $PWD bundle $*` to start-up
- Add an option to run a shell command before the ruby-lsp is loaded

I'll update the title of this issue to be more descriptive.

**Comment by andrewthauer** [comment]
I ran into a similar case trying to use [rtx](https://github.com/jdxcode/rtx) (new asdf clone written in `rust`). In theory the `none` version manager should have worked since `rtx` updates the `$PATH` on directory changes.

However, this didn't work and now I realize it is the same issue with `direnv`. The `chpwd` hook is probably run after (or never) in the context of the GUI load, so the path hasn't been updated with the correct ruby version. When I invoke `vscode` from the shell directory it inherits the environment and works well.

To get `rtx` working this could just be a matter of adding a new supported version manager. However, any solution to solve picking up the environment result of `direnv` would also allow this to work with `none` most likely. I use both `rtx` and `direnv` so my preference would be to have a solution that works by picking up the environment changes from tools that update the environment on directory changes rather then a specific `direnv` version manager.

I'm not familiar enough with what options are available for extensions, but I think a simple, but possible not elegant solution would be to allow for a pre `ruby-lsp` activate command to modify the environment. This could then allow running `direnv reload` or something else. However, perhaps there is a nicer solution here that doesn't require this sort of thing.
