### ISSUE TITLE
Expose detected Ruby version as a variable for customRubyCommand

### ISSUE THREAD

**Issue by Quintasan** [Shopify/vscode-ruby-lsp#640]
### This feature is VS Code specific

- [X] VS Code specific

### Use case

As described in https://github.com/Shopify/vscode-ruby-lsp/pull/523#issuecomment-1547802061 - using [rtx](https://github.com/jdxcode/rtx) is impossible now because `rtx activate` is meant to install the shell hook in the shell itself

The comment mentions being able to get it work in a prototype branch via `rtx exec ruby@${rubyVersion} -- ruby` so it means we need to add the Ruby version to the `customRubyCommand` for rtx to work

### Description

Make it possible to inject the Ruby version in executed `customRubyCommand`

**Comment by vinistock** [comment]
Where does `rtx` get the Ruby version string from? A `.ruby-version` file?

If that's the case, have you tried reading the version in the custom activation script? This will depend on your shell, but something like this
```shell
rtx exec ruby@$(cat .ruby-version)
```

**Comment by Quintasan** [comment]
> Where does `rtx` get the Ruby version string from? A `.ruby-version` file?
> 
> If that's the case, have you tried reading the version in the custom activation script? This will depend on your shell, but something like this
> 
> ```shell
> rtx exec ruby@$(cat .ruby-version)
> ```

rtx is asdf-clone so it uses `.tool-versions` which can have multiple tools specified in it so you can't exactly `cat .tool-versions` it

**Comment by Quintasan** [comment]
@vinistock I managed to wrangle `.tool-versions` into format but it still fails because vscode-ruby-lsp tries to execute the following command:

```
/bin/zsh -ic 'rtx exec ruby@$(cat .tool-versions | grep ruby | cut -d " " -f 4) && ruby --disable-gems -rjson -e "printf"'
```

which fails:

```
error: the following required arguments were not provided:
  <COMMAND>...

Usage: rtx exec <TOOL@VERSION>... -- <COMMAND>...

For more information, try '--help'.
```

What it should try to do is:

```
/bin/zsh -ic 'rtx exec ruby@$(cat .tool-versions | grep ruby | cut -d " " -f 4) -- ruby --disable-gems -rjson -e "printf"'
```

**Comment by vinistock** [comment]
The idea of the custom activation script is to do the changes to the environment as necessary - rather than being a `ruby-exec` style.

For example, if you were to do it for `chruby`, then you'd use `chruby` and not `chruby-exec`
```shell
/bin/zsh -ic 'chruby $(cat .ruby-version) && ruby --disable-gems -rjson -e "printf"'
```

Did you try activating the Ruby with RTX instead of using `rtx exec`?

**Comment by vinistock** [comment]
When I say activate, I'm not literally talking about the command, but the action to change the environment variables that will point your `ruby` executable to the right version.

For example, when you do `chruby 3.2.2`, it will change environment variables needed to select the correct version, like `RUBY_VERSION`, `GEM_HOME`, etc. Does `rtx` have an equivalent command that will set the correct environment variables for the select Ruby version?

In the command's result, you can see that none of those Ruby environment variables are present, which is why the extension was not able to find bundler.

**Comment by rolandcrosby** [comment]
`rtx env` outputs an `export PATH='...'` command, so this works:

```
  "rubyLsp.rubyVersionManager": "custom",
  "rubyLsp.customRubyCommand": "eval \"$(rtx env -s zsh)\"",
```

Note that this only sets `PATH`, I don't think rtx or its Ruby plugin set any of those other environment variables.

**Comment by Quintasan** [comment]
> `rtx env` outputs an `export PATH='...'` command, so this works:
> 
> ```
>   "rubyLsp.rubyVersionManager": "custom",
>   "rubyLsp.customRubyCommand": "eval \"$(rtx env -s zsh)\"",
> ```
> 
> Note that this only sets `PATH`, I don't think rtx or its Ruby plugin set any of those other environment variables.

This does appear to work, thanks @rolandcrosby
