### ISSUE TITLE
What mean 'relative path' for Gemfile? 

### ISSUE THREAD

**Issue by welcometotheparty** [Shopify/vscode-ruby-lsp#648]
Now I am working with ruby 2.5
Documentation contains "You can use separate Gemfile, just need fill relative path for that'

My prjoject folder /home/me/myapp
My Gemfile /home/me/work/Gemfile

What parh should I use for vsCode?

**Comment by welcometotheparty** [comment]
> I would expect it to be `"../work/Gemfile"`

I tried the absolute path (home/me/work/Gemfile), but it doesn't work
Ruby LSP still tries to use the ruby version local to the project

I cannot define a "starting point" for a relative path

**Comment by vinistock** [comment]
Closing this for now, please let us know if you're still unable to use the LSP.

**Comment by obahareth** [comment]
@vinistock This is also causing issues for me by being relative, I ideally would like to avoid using a Gemfile and just provide a path to be used globally (similar to the now deprecated Ruby VS Code extension).

All my project workflows are using Docker and Docker Compose, so I can't rely on gems installed at the project-level, and I need globally-available paths.

I did setup a `~/.ruby-lsp/Gemfile` to use it globally, but since the bundle path is relative, I need to keep changing it for every project I open.

Would it be possible to support absolute paths here?
