### ISSUE TITLE
Add a Changelog to the extension in the VSCode Marketplace

### ISSUE THREAD

**Issue by renchap** [Shopify/vscode-ruby-lsp#734]
### This feature is VS Code specific

- [X] VS Code specific

### Use case

When updating the extension, you need to goto the repository, then check the latest Github Release for changes.

### Description

Some extensions display a very useful "Changelog" tab when viewed in the VSCode marketplace.

For example:
<img width="746" alt="image" src="https://github.com/Shopify/vscode-ruby-lsp/assets/42070/7aecb1d9-67b9-4e87-a98f-54a8ede29e8c">

### Implementation

I think this works automatically when you have a `Changelog.md` file in your extension, as I could not find a field in `package.json` to configure it.

This changelog could be automatically generated when publishing a new version, as the content is already in Github Releases

**Comment by abhikumar63** [comment]
Hey,
I have seen the requirements of this task and I am very comfortable in doing the same for you. I have seen the example cases for various other extensions.
Can I contribute to this project for this task.

**Comment by vinistock** [comment]
Notice that we explicitly removed `CHANGELOG.md` because we didn't want to maintain the changelog manually. We use GitHub release automation to generate the release notes.

We will not accept changes that will involve manual steps for making releases. If this issue is to be completed, it'll have to be with automation connected to creating GitHub releases through the UI.

If you have a suggestion on how to automate this, feel free to propose an implementation.
