### ISSUE TITLE
Using ASDF with a 2.7 project, getting: Failed to activate asdf environment: The Ruby LSP requires Ruby 3.0 or newer to run. Please upgrade your Ruby version

### ISSUE THREAD

**Issue by willmakley** [Shopify/vscode-ruby-lsp#821]
### Operating System

Ubuntu 22

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

asdf

### Description

I don't know if this is a bug. My project uses Ruby 2.7.6, specified in .tool-versions and Gemfile. I have Ruby 3.2.2 installed separately for use by Ruby LSP, yet I get this error. Am I doing something wrong? Is this not supported? Is it a bug?

For some reason Ruby LSP does not seem to be creating the ".ruby-lsp" directory, and just throws that error.

```sh
$ asdf list ruby
  2.7.6
  3.2.2
```

```sh
$ cd $PROJECT
$ cat $PROJECT/.tool-versions
ruby 2.7.6
nodejs 14.19.0
yarn 1.22.19
```

Gemfile:
```ruby
source 'https://rubygems.org'

ruby '2.7.6'
```

.vscode/settings.json:
```json
{
    "rubyLsp.rubyVersionManager": "asdf",
    "rubyLsp.formatter": "auto",
    "rubyLsp.enableExperimentalFeatures": false,
}
```

**Comment by vinistock** [comment]
Thank you for the bug report! By default, the Ruby LSP will always try to use the Ruby version and dependencies specified in the project. If the project uses an EOL Ruby version, you'll need to create a separate folder with a Gemfile and another .tool-versions file specifying the Ruby version you'd like to use.

You can follow the instructions [here](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#using-a-custom-gemfile).

**Comment by vinistock** [comment]
The server automatically creates a custom bundle in the `.ruby-lsp` folder when

- `rubyLsp.bundleGemfile` is not set. Since you're pointing to a different Gemfile, there's no need to create the custom bundle in `.ruby-lsp`
- Your project's Gemfile doesn't have the `ruby-lsp` or the `debug` gem - which we need to provide LSP and debugging functionality

You never need to create a `.ruby-lsp` folder manually. When using `bundleGemfile`, you basically need to manage that separate bundle yourself. Add any gems that are relevant for your project (like RuboCop), configure the Ruby version with your manager and handle updates whenever there's a new `ruby-lsp` version out.
