### ISSUE TITLE
LSP Server keeps crashing under Windows

### ISSUE THREAD

**Issue by esb** [Shopify/vscode-ruby-lsp#831]
### Operating System

Windows 10/11

### Ruby version

3.2.2

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

no manager

### Description

My code is on a Windows machine which is rsynced to a virtual machine running the test environment.

As such, I have a Gemfile, but no Gemfile.lock in the Windows environment. I do not install the bundle gems, and in some cases, I can't install certain gems as they rely on native C code that won't compile in the mingw-64 environment.

For reasons I don't understand, ruby-lsp is insisting that I need to have a Gemfile.lock and repeatedly crashes and restarts.

How do I stop this behaviour?

**Comment by vinistock** [comment]
Thank you for the bug report!

The Ruby LSP's default behaviour is to use the gems that are a part of the bundle to provide formatting and to know which paths to index automatically so that you can get go to definition, hover, etc.

I don't fully understand your workflow yet. You never install gems in your local machine so there's never a lockfile? If you wanted to run a formatter, like `bundle exec rubocop`, how would you do it?

Also, if certain gems can't be compiled on Windows, you can always add platform constraints in the Gemfile so that you only install compatible gems. This is what the [Ruby LSP itself does for Sorbet](https://github.com/Shopify/ruby-lsp/blob/212d8dde0096897b30360de87cb6e1be88188df5/Gemfile#L22), which doesn't support Windows.

**Comment by esb** [comment]
The code base is not stored on the virtual server, but is kept on Windows. This allows it to be backed up and replicated easily. The code is rsynced to the virtual machine to do the build, etc but it is edited from Windows.

I understand that Ruby LSP can do nice things if the gem bundle is available, but in certain complex builds this is just not possible in a Windows environment. All I'm looking for is a way to use Ruby LSP without having the gems available.

**Comment by vinistock** [comment]
Are you able to install any gems on the Windows side? It won't be possible with absolutely no gems installed given that the server itself is a gem - so at least that needs to be installed.

If you can, then you can create a separate `Gemfile` from the project with just the `ruby-lsp` gem inside of it and configure VS Code to always use that on every project. The instructions are [here](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#using-a-custom-gemfile).

**Comment by esb** [comment]
I've tried the platforms workaround and added `platforms: [:ruby]` to a bunch of the troublesome gems that can't compile natively under Windows. That seems to be enough to keep `ruby-lsp` happy.

**Comment by vinistock** [comment]
Glad to hear that. I'll close the issue for now, but please let us know if you find other issues.
