### ISSUE TITLE
Debugging rails app

### ISSUE THREAD

**Issue by stage-rl** [Shopify/vscode-ruby-lsp#832]
### Operating System

Debian Linux

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

Hello, tried to use the debugger for rails apps in "attach mode" and gave up several times returning to [vscode-rdbg](https://github.com/ruby/vscode-rdbg)

Only after seeing [this](https://github.com/Shopify/vscode-ruby-lsp/issues/829#issuecomment-1759862059) comment I tried running my rails app as `bundle exec rdbg --open --command --sock-path=/tmp/ruby-lsp-debug-sockets/test.sock -- bin/rails server -p 3000` and it works. This still required to manually create /tmp/ruby-lsp-debug-sockets folder.  Still this is probably not the required approach.

Can you pls add info on proper procedure to README? Thanks a lot and keep up the good work

**Comment by vinistock** [comment]
Thank you for the bug report! I'm puzzled as to how it worked without any manual intervention in `vscode-rdbg`.

The only way to attach to an existing Ruby process is if that process was started with the debugger in the first place. Do you have any `rdbg` configuration?

When you attach with `rdbg`, how do you launch the server?

**Comment by stage-rl** [comment]
With `vscode-rdbg` it was slightly simpler `rdbg -O -n -c -- bin/rails server -p 3000`

**Comment by vinistock** [comment]
The idea of the socket path is that we create those automatically for you when launching the debugger, so that you don't have to configure or select anything.

For attach, it's a bit different though. The extension has no way of knowing where the socket was created, so that it can offer as an option for you to select.

In terms of the command, I'm pretty they are equivalent, we're just using the long names for the arguments (i.e.: `--open` instead of `-O`).

The Ruby LSP debug client will default to look for sockets inside `/tmp/ruby-lsp-debug-sockets`.

@st0012, in retrospect that was a bit of an odd decision from our part. If you don't specify a `sock-path`, does Ruby debug always put the sockets in the same folder? Maybe we should change this to use whatever it does by default.

**Comment by vinistock** [comment]
FWIW, it's already possible to launch a Rails server with the debugger using the configuration Stan mentioned. But in this attach scenario, it's definitely not clear.

I think we should

- Mention in the [debugging documentation](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#configuring-vs-code-debugger) that the sock-path needs to be inside `/tmp/ruby-lsp-debug-sockets`
- Enhance our quick pick logic so that if there are no sockets to select, we inform the user. Maybe show a message saying `No sockets found in /tmp/ruby-lsp-debug-sockets. See [debugging]() for more information.` and then we link to the README from that message

@stage-rl are you interested in taking a stab at any of these two?

**Comment by tomascco** [comment]
> Now back to the main question, I think we can probably just provide an example config entry for Rails apps, like:
> 
> ```
>     {
>       "type": "ruby_lsp",
>       "name": "Debug Rails Server",
>       "request": "launch",
>       "program": "bin/rails server -p 3000"
>     },
> ```
> 
> And when users want to debug Rails apps, they use this action to start the server, which will automatically be attached with VS Code. @stage-rl would that work for you?

What I'm currently doing in my Rails app is to use the following initializer:
```ruby
# frozen_string_literal: true

if Rails.env.development?
  FileUtils.mkdir_p("/tmp/ruby-lsp-debug-sockets/")
  DEBUGGER__.open(nonstop: true, sock_path: "/tmp/ruby-lsp-debug-sockets/development.sock")
end
```

I like this approach because the debugger is always ready to be attached, I don't need to stop the server and start it again to investigate some issue. It's similar to what @stage-rl is doing, but I also like the fact that I don't need to write a complicated command or use an alias, just plain `rails s`.

**Comment by stage-rl** [comment]
Hi, my first implementation (with no error handling) that works for implicitly generated sockets for remote debugging can be found here:
https://github.com/Shopify/vscode-ruby-lsp/commit/86d3aa7a65cc12aae074ceaaf6bd02cd5a109e03

I have never modified a vscode extension, so I'm kind of lost on how to proceed. Pls point me in the right direction. Thanks

**Comment by stage-rl** [comment]
I will do that next week when I return from holiday
