### ISSUE TITLE
Trying to work with a custom gemfile doesn`t work

### ISSUE THREAD

**Issue by lucasldemelo** [Shopify/vscode-ruby-lsp#849]
### Operating System

MacOS

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

chruby

### Description

I'm trying to set up RUBY LSP to run on VSCode. We have a project that is currently running in Docker with version 2.7.7, and even following the tutorial in the README, it's not working.

I tried creating the folder with version 3.2.2, but whenever I try to run the project, the following error is given: "Failed to activate chruby environment: The Ruby LSP requires Ruby 3.0 or newer to run. Please upgrade your Ruby version."

It seems like it's completely ignoring the configuration in settings:

"rubyLsp.bundleGemfile": "/Users/lucasluan/Documents/Work/utils/Gemfile"

**Comment by rafaelvebercarvalho** [comment]
I had the same problem, but using rbenv. Even after creating a separate folder with the Gemfile and ruby-version and changing the path, it was still pulling the Ruby version from the project.

**Comment by vinistock** [comment]
Thank you for the bug report! For `chruby`, we were indeed not looking into the correct directory to read the `.ruby-version` file. This https://github.com/Shopify/vscode-ruby-lsp/pull/851 should fix it.

I'm not so sure about `rbenv` though. We were already running `rbenv exec ruby` in the right directory - so the activated version should be the right one.

However, we were displaying the incorrect version in the language status item - if that's what you mean. That is also fixed by #851.
