### ISSUE TITLE
Failed to activate none environment Ruby LSP (extension) on Windows 10 with the ruby-3.2.2 version

### ISSUE THREAD

**Issue by SaidRasinlic** [Shopify/vscode-ruby-lsp#883]
### Operating System

Windows 10

### Ruby version

3.2.2

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

no manager

## Here is the error screenshot: 
![Ruby-Lsp-Error](https://github.com/Shopify/vscode-ruby-lsp/assets/57558480/b1d35c0f-3e5d-4dcd-a549-e281d562d5bd)

### Thank you in advance!

**Comment by vinistock** [comment]
Thank you for the bug report! I created #885 to address the issue with spaces in the shell path.

Notice that if you're not using a version manager, you may still need to configure the [custom activation](https://github.com/Shopify/vscode-ruby-lsp/blob/main/VERSION_MANAGERS.md#custom-activation) to add Ruby to the `PATH`, so that the extension can find it.
