### ISSUE TITLE
rdebug-ide support

### ISSUE THREAD

**Issue by thomthom** [Shopify/vscode-ruby-lsp#903]
### This feature is VS Code specific

- [X] VS Code specific

### Use case

I'm developing against Ruby embedded into desktop applications. To debug Ruby in this environment I've been using the `rdebug-ide` protocol. 

I've been using the Ruby VSCode extension by Peng Lv (https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) to use this interface via VSCode. Now this VSCode extension is deprecated and it directs to Ruby LSP as the path forward.

### Description

Support for the rdebug-ide protocol to replace the integration that was provided by the "Ruby" VSCode extension.
https://github.com/ruby-debug/ruby-debug-ide

### Implementation

No any specific suggestions, I can only point to what I've been using up til this point:
https://github.com/rubyide/vscode-ruby/blob/main/docs/debugger.md

**Comment by thomthom** [comment]
For some more background, the Ruby interpreter is embedded into the application (SketchUp) to provide extension/plugin capabilities. This means that the Ruby version is locked to whatever version it shipped with. Over the years various versions has been used (2.0, 2.2, 2.5, 2.7). The latest version is currently using 2.7 but 3.x is in progress for a future release. However, an extension develop still have to deal with older versions of the application and thus versions of Ruby such as 2.7 and 2.5.

A debugger addon is provided to extension developer that needs to debug Ruby in the application: https://github.com/SketchUp/sketchup-ruby-debugger

This uses the `ruby-debugger-ide` protocol which works in multiple IDEs across Ruby versions.

If Ruby LSP can be connected to that protocol that'd work. Though I don't see from the docs how that would work?

**Comment by st0012** [comment]
VS Code uses an open, language-agnostic protocol called [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol), which is what the official `debug` gem supports natively. So unfortunately we don't plan to support any additional protocols required by non-official Ruby debugger.

That said, I'm aware that you're project is not able to adopt `debug` due to Ruby version support. So here's something you may want to try:
1. Build your debugger addon on top of DAP instead
2. Switch to `byebug`, which supports Ruby 2.x as well as DAP through [`byebug-dap`](https://gitlab.com/firelizzard/byebug-dap)
3. Then you can adopt [`VSCode Byebug Debugger`](https://marketplace.visualstudio.com/items?itemName=ethan-reesor.vscode-byebug) as the VS Code extension for it

It's not a small task but for the project's long term development, especially for Ruby 3.0+ support, I think it'll be beneficial.

**Comment by thomthom** [comment]
Thanks for the consideration and suggestions.

I'm wondering... the Ruby debug gem states that it works back to Ruby 2.6. Maybe that's enough going forward. So if we can get the `debug` gem working - should Ruby LSP work out of the box then?

The LSP debugging doc describes the debug config as:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "ruby_lsp",
      "request": "attach",
      "name": "Attach to existing server"
    }
  ]
}
```
Is that all the config there is for remote debugging? No ports to configure?
