### ISSUE TITLE
RubyLSP problem

### ISSUE THREAD

**Issue by Gatoloko44** [Shopify/vscode-ruby-lsp#925]
### Operating System

Windows 11

### Ruby version

ruby 3.2.2

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

no manager

### Description

![image](https://github.com/Shopify/vscode-ruby-lsp/assets/104461747/747212fa-3238-4788-af56-983ad95c8ec4)
yesterday the extension show me this error and i don't make any change in my computer or visual

**Comment by Gatoloko44** [comment]
That's very strange on my computer it works fine but i don't know why in yours doesn't works

**Comment by vinistock** [comment]
I made a [release](https://github.com/Shopify/vscode-ruby-lsp/releases/tag/v0.4.22) reverting that change while we understand the problem better.

**Comment by vinistock** [comment]
@SaidRasinlic thank you for sharing that video, it helps better understand the problem. It looks like writing to the temporary file succeeds, but then it gets immediately removed (possibly by antivirus software?).

In that case, we won't be able to fix problems like #882 (where the STDERR pipe is hijacked by a shell plugin) until #923 is finished and shipped (which decouples the extension from the shell).

I'll close this issue for now since we reverted the PR that caused trouble.
