### ISSUE TITLE
The Ruby LSP requires Ruby 3.0 or newer to run.

### ISSUE THREAD

**Issue by SeifESlimene** [Shopify/vscode-ruby-lsp#948]
Hello,

I was using ruby vscode extension of peng Lv with ruby 2.6.2, but now with that extension is deprecated and Ruby LSP come in place, my ruby version is not supported by this extension and a popup appears in vscode that says:

Failed to activate rbenv environment: The Ruby LSP requires Ruby 3.0 or newer to run. This project is using 2.6.2.         
[See alternatives](https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#ruby-version-requirement)

Why this is not backward compatible, like I was using ruby extension before?!!

![ruby-lsp](https://github.com/Shopify/vscode-ruby-lsp/assets/57100260/66b688d7-ee55-41e8-988a-619011ef4ea7)

**Comment by andyw8** [comment]
@SeifESlimene we need more information in order to help you. For example, are you seeing any output or errors in Ruby LSP output tab? Can you share the contents of your custom Gemfile?

**Comment by st0012** [comment]
We need to require Ruby 3.0 because the main dependency of this project, [Prism](https://github.com/ruby/prism), requires that version. And even if it did loosen the version requirement a bit (which requires extra work and doesn't seem to be planned), it'd only be 2.7 instead of 2.6. And as additional reference: both [IRB](https://github.com/ruby/irb) and [Ruby's official debugger](https://github.com/ruby/debug) requires Ruby 2.7+ now. 

Finally, Ruby 2.6 has entered EOL 1.5 years ago, which means it will only become more and more vulnerable without receiving further updates.

So I'd really recommend you to use this opportunity to prioritise related upgrade work (which is likely fewer than you expect now) instead. It'll make your application more secure and allow it to have access to better tooling 🙂

**Comment by lectricas** [comment]
damn you guys. If you depricate something, provide a good and clear step by step guide on how to install things. 
deprecate yourself please

**Comment by paracycle** [comment]
> damn you guys. If you depricate something, provide a good and clear step by step guide on how to install things. deprecate yourself please

I think you are grossly mistaken about who deprecated what, and your tone is NOT appropriate. The older `rebornix.Ruby` VSCode extension has nothing to do with our team, and its deprecation was a decision that was made by its author. Nothing to do with us and nothing we can control.

Thank you!
